FROM node:15
# FROM ubuntu:latest

RUN apt-get update
RUN apt-get install apache2-utils -y
# RUN mkdir -p app/src
# WORKDIR /app
# ADD package.json .
# RUN npm install
# ADD ./src ./src
# CMD ["node", "./src/index.js"]
