version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  one: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/node:10.0.0 # specifically, a docker image with ruby 2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - run: 
          working_directory: backend
          command: |
            npm install
            npm list | grep jest
      - run: 
          working_directory: backend
          command: |
            npm list | grep jest
      - run:
          working_directory: backend
          command: |
            npm install --save-dev jest
            npm run test
# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2
  one: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - one